In [2]:
import tensorflow as tf

### 1. Naći indeks najmanje i najveće vrednost u datim tenzorima. Probati sa različitim osama tenzora.

In [96]:
a = tf.constant([1, 4, 10, 50, 0, 10, 2, 3], name='a')
b = tf.constant([[10, 1, 2], [1, 0, -1], [-2, 13, 0]], name='b')

with tf.Session() as sess:
    
    print(sess.run(tf.argmin(a, 0)))
    print(sess.run(tf.argmin(b, axis=0)))
    
    print(sess.run(tf.argmax(a, 0)))
    print(sess.run(tf.argmax(b, axis=0)))

4
[2 1 1]
3
[0 2 0]


### 2. Naći prosek u tenzoru. Probati sa različitim osama tenzora.

In [100]:
a = tf.constant([[1200, 130], [50, 10], [900, 1200]])

with tf.Session() as sess:
    
    print(sess.run(tf.reduce_mean(a)))
    print(sess.run(tf.reduce_mean(a, axis=0)))
    print(sess.run(tf.reduce_mean(a, axis=1)))

581
[716 446]
[ 665   30 1050]


### 3. Naći sumu tenzora. Probati sa različitim osama tenzora.

In [101]:
a = tf.constant([[1, 3], [2, 0], [0, 1]])

with tf.Session() as sess:
    
    print(sess.run(tf.reduce_sum(a)))
    print(sess.run(tf.reduce_sum(a, 0)))
    print(sess.run(tf.reduce_sum(a, 1)))

7
[3 4]
[4 2 1]


### 4. Naći prosek random tenzora oblika (4, 3) koji se dobija iz normalne raspodele sa proskom $\mu=5$ i standardnom devijacijom $\sigma=7$. Obratiti pažnju da je neophodno raditi proske po kolonama.

In [109]:
norm = tf.Variable(tf.random_normal([4, 3], mean=5, stddev=7))

with tf.Session() as sess:
    
    sess.run(tf.global_variables_initializer())
    
    print(sess.run(norm))
    
    print(sess.run(tf.reduce_mean(norm, 0)))
    
    print(sess.run(norm))

[[ 8.113598  -5.6435156  8.954301 ]
 [12.320296  11.368067   0.9636698]
 [ 2.5194013 16.042938   1.8242159]
 [ 9.144661   8.56468    2.8091257]]
[8.024489  7.5830426 3.637828 ]
[[ 8.113598  -5.6435156  8.954301 ]
 [12.320296  11.368067   0.9636698]
 [ 2.5194013 16.042938   1.8242159]
 [ 9.144661   8.56468    2.8091257]]


### 5. Napisati program koji rešava dati sistem linearni jednačina.
$$
    \begin{array}{c} 
    a_{11}x + a_{12}y = b_{11} \\ 
    a_{21}x + a_{22}y = b_{21} \\ 
    \end{array} 
$$

In [116]:
A = tf.Variable(tf.zeros([2, 2]), dtype=tf.float32)
B = tf.Variable(tf.zeros([2, 1]), dtype=tf.float32)

X = tf.matmul(tf.matrix_inverse(A), B)

with tf.Session() as sess:
    
    print(sess.run(X, feed_dict={A:[[3, 2], [4, -1]], B:[[15], [10]]}))

[[3.1818182]
 [2.7272727]]


### 6. Napisati program koji nalazi rešenja kvadratne jednačine oblika $ax^{2} + bx + c$, za proizvoljne $a, b, c$ koeficijente, pri čemu $a\ne 0$.

In [113]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
c = tf.placeholder(tf.float32)

d = tf.sqrt(tf.pow(b, 2) - 4*a*c)

x1 = tf.divide(-b + d, 2*a)
x2 = tf.divide(-b - d, 2*a)


with tf.Session() as sess:
    
    print(sess.run([x1, x2], feed_dict={a:1, b:5, c:6}))
    
    print(sess.run([x1, x2], feed_dict={a:5, b:6, c:1}))

[-2.0, -3.0]
[-0.2, -1.0]


### 7. Naći minimum funkcije $y=x^2$ korišćenjem [Gradijentalnog spusta](https://en.wikipedia.org/wiki/Gradient_descent), iterativnog algoritma za optimizaciju.
Hint : tf.train.GradientDescentOptimizer(learning_rate).minimize(function)

In [30]:
x = tf.Variable(2.0, dtype=tf.float32, name='x') 
y = tf.pow(x, 2)

In [31]:
learning_rate = 0.001
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(y)

In [37]:
with tf.Session() as sess:
    
    sess.run(tf.global_variables_initializer())

    print(sess.run([x, y]))

    sess.run(x.assign(4.0))
    print(sess.run([x, y]))
    
    for i in range(1):
        
        sess.run(optimizer)
        
        if i % 1000 == 0:
            print("iteration: %4d, x: %4f" % (i, sess.run(x)))
        
    print("Minimum of function is y=%d at value x=%d" % (sess.run(y), sess.run(x)))

[2.0, 4.0]
[4.0, 16.0]
iteration:    0, x: 3.992000
Minimum of function is y=15 at value x=3
